### ISSUE TITLE
Online Help Search for 1-2 characters

### ISSUE THREAD

**Issue by suever** [suever/MATL-Online#22]
To help in finding MATL statements, it would be nice to treat 1-2 character search strings as literals rather than smart search. This would result in `T` matching the statement `true` rather than all possible "T" occurances

**Comment by lmendo** [comment]
My original suggestion was to treat the following as literals: either 1-char strings or 2-char strings _that begin with `X`, `Y`, `Z`_. But if it simplifies the code, treating all 2-char strings as literals is probably fine.

**Comment by suever** [comment]
@lmendo So would you expect them to be case-sensitive or insensitive? (i.e. "XN" would yield `Xn` and `XN` or just `XN`)

**Comment by suever** [comment]
I just pushed a change to the site, so check it out and see if it behaves as you expect. For now I have it case sensitive and it triggers the statement search when the search string is either a single character or it's two characters and starts with an X, Y, or Z.

**Comment by lmendo** [comment]
@suever I think it's perfect as it is! Thank you! Yes, I think it makes sense to do only statement search, not mentions
