### ISSUE TITLE
Octave not successfully being killed

### ISSUE THREAD

**Issue by suever** [suever/MATL-Online#26]
After a certain amount of time (or the types of jobs), the `octave` process isn't properly killed and then it is unable to startup again which just causes the CPU to churn and the memory gets consumed until celery ultimately crashes due to no available RAM.

I suspect that this happens when the directory in which octave is running is removed and there is some stored state within Octave that tries to load that directory when starting. 

To fix this, there are two main things to address:

1) Make sure that Octave is completely killed 

2) Make sure that each Octave session that boots is completely independent of previously-run sessions. I think this can be done through a combination of command line switches such as: `octave-cli --norc --no-history`

Even when we _can_ launch octave with all of these command line switches, it never exits and when we finally force kill everything, we get the following:

> attempting to save variables to 'octave-workspace'...
> save to 'octave-workspace' complete
> save to 'octave-workspace' complete

It may be that we are having issues with it attempting to save the crash files when we kill jobs from within celery. We should add the following to prevent crash files from being saved

```
crash_dumps_octave_core(false);
```

[Documentation](http://octave.sourceforge.net/octave/function/crash_dumps_octave_core.html)

**Comment by suever** [comment]
This change has been made and deployed. Will monitor logs and see if we have any future issues.

**Comment by suever** [comment]
Adding these options looks like it *may* be causing some issues as the server has app has gone down twice now complaining that it can't find `oct2py.octave` which is because `oct2py` is unable to find octave. Not sure why that would be the case.

**Comment by suever** [comment]
I think that we can go ahead and mark this as resolved. I made a [small modification to the `oct2py` library that we are using](https://github.com/suever/oct2py/commit/16db760302111a32d40cc47c5a155cc12897ae3f) which allows you to specify additional inputs to octave at the command line. In this way, I can force octave to start with a fresh slate every time rather than trying to reload a previous (broken) state. We've been up and running for 8 days without issue since then.

**Comment by lmendo** [comment]
Yes, it's been running fine for long now. Good job! :-)
