### ISSUE TITLE
Freezing documentation on Android

### ISSUE THREAD

**Issue by suever** [suever/MATL-Online#27]
Conversation and information available [here](https://chat.stackexchange.com/transcript/message/32428599#32428599)

**Comment by lmendo** [comment]
To add to the description: what I have noticed on my mobile (Android 6.0) is that it responds slowly, and seems to become gradually slower, sometimes to the point of freezing, sometimes just very slow

**Comment by suever** [comment]
@lmendo Thanks for the info. Is it slower when opening it multiple times within the same session or is it slower the second time even if you reload the page?

**Comment by lmendo** [comment]
I have just tested it a few times. I couln'd get it to freeze (did you change anything?). What I find, in the first or subsequent searches, is that after typing each letter the phone takes about half a second to response, as if updating the search after each new letter was costly. Maybe it's normal behaviour

**Comment by suever** [comment]
@lmendo  I haven't changed anything. It could just be that the javascript engine on the Android devices isn't the fastest. I do _slightly_ modify the searching since we want 1-2 character matches to look for MATL symbols directly. Could you try searching on the table [at this link](https://datatables.net/examples/basic_init/zero_configuration.html) to see if it is also relatively slow? Granted, they only have 57 entries in that table. 

I may be able to mock up a test page for you where I remove my custom search and we can see if that's the issue.

Let me know how that above table works.

**Comment by lmendo** [comment]
@suever It is much faster with that table. Perhaps there's a very small delay too, but I'm not even sure. On the other hand, since the table is daster form MATL, maybe it's just normal that it takes time on an Android device

**Comment by lmendo** [comment]
I tested on my iPad Air with iOS 10. It is not as slow as on my Android 6.0 phone, but you can notice the same type of behaviour: a noticeable delay between typing each subsequent key and seeing the updated results. So maybe it's just the normal behaviour on a mobile device

**Comment by suever** [comment]
Going to go ahead and mark this resolved since the last few fixes improved the mobile experience. If needed we can reopen to tweak the settings and possibly allow for a more-responsive search on desktops.
