### ISSUE TITLE
Incorporate support for audio output

### ISSUE THREAD

**Issue by suever** [suever/MATL-Online#32]
MATL [now](https://github.com/lmendo/MATL/commit/03e9749719126024bc1c3cb79039ad24aa8f531c) has an implementation of `sound`, `soundsc`, and `audiowrite` to produce audio output. They need to be overloaded in our `.octaverc` file so that an mp3 file is generated on the server and then streamed back to the client. Each separate sound should appear as it's own `<audio>` block which will automatically get the browser's native audio controller.

**Comment by lmendo** [comment]
If I recall correctly, `soundsc` calls `sound` to produce the actual sound. So no need to overload that one

**Comment by suever** [comment]
@lmendo  Ah great point!

**Comment by suever** [comment]
A version of this has been merged in and deployed.

[Example](https://matl.suever.net/?code=%25+Create+values+of+t+from+0+-+1+seconds+at+44100+Hz%0A0+l+44100+%2F+1+3%24%3A+2YP+%2a+%2a+XJx%0A%0A%27C-Major%3A%27D%0AJ+261.626+%2a+X%2C+J+329.628+%2a+X%2C+%2B+J+391.995+%2a+X%2C+%2B+TY%23%0A%0A%27F-Major%3A%27D%0AJ+261.626+%2a+X%2C+J+349.228+%2a+X%2C+%2B+J+440.000+%2a+X%2C+%2B+TY%23%0A%0A%27G-Major%3A%27D%0AJ+246.942+%2a+X%2C+J+293.665+%2a+X%2C+%2B+J+391.995+%2a+X%2C+%2B+TY%23&inputs=&version=20.6.0)
