### ISSUE TITLE
Some plot functions like `bar` do not work online

### ISSUE THREAD

**Issue by lmendo** [suever/MATL-Online#345]
I just added a few plotting functions like `bar`, `stem`, `surf` etc in `YH`.  They work offline in Octave, but not online. Any idea what may be going on? Test: this should give a bar plot

https://matl.suever.net/?code=K%3A++%25+Range+from+1+to+4%0A5YH+%25+bar&inputs=&version=b3fd427d

It doesn't produce any output, nor an error

**Comment by suever** [comment]
The way that we trigger a screenshot in the online interpreter is via the `drawnow` command. All of the other plot/display commands automatically trigger a `drawnow` according to the documentation but these news ones you added do not mention doing the same. 

If we add a command that *does* call a `drawnow`, then we see the image rendered ([example](https://matl.suever.net/?code=K%3A++%25+Range+from+1+to+4%0A5YH+%25+bar%0A%27equal%27lZG&inputs=&version=b3fd427d))

MATL should probably automatically call `drawnow` for all variants of `YH` I would think to be consistent.

**Comment by lmendo** [comment]
You are totally right. I knew we had to something to make graphical stuff work, but I didn't remember what it was. Solved now. Closing issue. Thanks!
