### ISSUE TITLE
Buttons only show text on iOS 11.2

### ISSUE THREAD

**Issue by lmendo** [suever/MATL-Online#38]
On iOS 11.2 buttons are shown without border or background (both on iPhone and iPad). So only the text is seen, as illustrated in this image

https://chat.stackexchange.com/transcript/message/41573550#41573550

No big deal of course, just aesthetics. Other than that, the buttons work as expected

**Comment by suever** [comment]
@lmendo Thanks for pointing this out, I'll try to look into it soon!

**Comment by suever** [comment]
@lmendo Just pushed a fix for this. Let me know if it looks good to you now!

**Comment by lmendo** [comment]
It looks good now! Thanks
