### ISSUE TITLE
MATL Online not responding

### ISSUE THREAD

**Issue by lmendo** [suever/MATL-Online#631]
For example:

https://matl.suever.net/?code=%2B&inputs=2%0A3&version=22.4.0

Maybe it needs some restarting?

I hope you are doing well!

**Comment by suever** [comment]
> For example:
> 
> https://matl.suever.net/?code=%2B&inputs=2%0A3&version=22.4.0
> 
> Maybe it needs some restarting?
> 
> I hope you are doing well!

Thanks for the report! The cloud provider did have some maintenance yesterday so that's likely what caused the issue. It is working now after a quick restart.

**Comment by lmendo** [comment]
Thank you!
