### ISSUE TITLE
Domain is down?

### ISSUE THREAD

**Issue by lmendo** [suever/MATL-Online#770]
Hello! You've probably noticed, but just in case, matl.suever.net and even suever.net seem to be down

**Comment by suever** [comment]
@lmendo Thanks for pointing this out! I'll take a look at it and see about getting that working. In the meantime, you can use https://matl.suever.com instead!

**Comment by lmendo** [comment]
That's great, thank you! I'll post the new URL in the chat room so people can use it

**Comment by suever** [comment]
Sorry this took so long to resolve but now both should be working :sweat_smile:

**Comment by lmendo** [comment]
Thank you! The general domains (`suever.com`, `suever.net`) are up, but `matl.suever.com` and `matl..suever.net` give a "500 internal server error" for me. Can you check that?

**Comment by suever** [comment]
@lmendo Thanks for the heads up. Should be resolved but I'll keep an eye on it!

**Comment by lmendo** [comment]
Thank you! Working now on both domains. I'll let you know if there's any issue. Do you intend to keep both domains, or eventually just one?

**Comment by suever** [comment]
> Thank you! Working now on both domains. I'll let you know if there's any issue. Do you intend to keep both domains, or eventually just one?

Eventually I may implement a redirect from the .net to the .com but even then they will both work because there are lots of old answers relying on the old one

**Comment by lmendo** [comment]
That's so nice of you! Huge thanks!

**Comment by suever** [comment]
@lmendo Went ahead and setup matl.io and redirected all of the *.suever.* subdomains to reduce confusion and give us a nice stable domain. Also updated all links that I could find on SE (sorry for the spam!). Let me know if you run into any issues.

**Comment by lmendo** [comment]
@suever Thanks for all the work! So, is `matl.io` the one to use from now on?

**Comment by suever** [comment]
> @suever Thanks for all the work! So, is `matl.io` the one to use from now on?
> 
> 
> 
> 

Yes, but users will automatically be redirected to it if they put in the old addresses

**Comment by lmendo** [comment]
That's great!
  I have found a small issue. Actually two, which might be related:

 `colormap` does not update the image, see [here](https://matl.io/?code=3Xy++++++++++++%25+3x3+identity+matrix%0A1YG++++++++++++%25+imagesc%0A%5B1+0+0%3B+0+1+0%5D+%25+define+colormap%3A+green+and+red%0A2ZG++++++++++++%25+set+colormap+&inputs=&version=b3fd427d). Based on some answers, this used to work. That's no big deal, because it coud be worked around by first setting the colormap and then plotting the image. But that doesn't work now because the call to `colorbar` seems to leave something weird on the stack, and the code errors for example if it tries to concatenate the stack with `v`. See this [minimal example](https://matl.io/?code=%5B1+0+0%3B+0+1+0%5D+%25+define+colormap%0A2ZG++++++++++++%25+set+colormap+%28consumes+the+input%29%0AND+++++++++++++%25+display+number+of+elements+in+stack.+Should+be+0%2C+but+it+is+1%0AX%23+++++++++++++%25+inspect+stack.+Should+be+empty.+Instead+it+begins+to+display+something+and+gives+an+error&inputs=&version=b3fd427d)

Could it be related to [this](https://github.com/suever/MATL-Online/issues/345#issuecomment-533021916)?  (that is, have you implemented the modified version of `drawnow` in the new interpreter? Or have you maybe updated the Octave version? If so let me know which one you are using so I can test

**Comment by lmendo** [comment]
Perhaps you cuould send me the generated `MATLc.m` of the last example so I can take a look.

If you prefer we can continue in [chat](https://chat.stackexchange.com/rooms/39466/matl-chatl).

**Comment by lmendo** [comment]
Not sure if you get a ping automatically. Just in case: @suever ^
