### ISSUE TITLE
Server not responding

### ISSUE THREAD

**Issue by lmendo** [suever/MATL-Online#84]
Could you reboot it? Thanks! I hope everything's going well

**Comment by suever** [comment]
Sorry about that, just restarted and it seems to be working again! It ran into an error because it had been running so long without having to be restarted! I'm doing great, hope you're doing well too. Hopefully I'll be back to golfing soon ;)

**Comment by lmendo** [comment]
Hey, thanks! MATL may be chosen ["language of the month"](https://codegolf.meta.stackexchange.com/questions/14737/nominations-for-language-of-the-month) in May. If so, we'll have to keep an eye on the server :-)
