### ISSUE TITLE
Can you restart the server?

### ISSUE THREAD

**Issue by lmendo** [suever/MATL-Online#85]
It's not responding, at least for me. Thanks!

**Comment by suever** [comment]
Done @lmendo! I'll hopefully get to spend some time on this soon to get that to stop happening!

**Comment by lmendo** [comment]
Thanks, working now! I know you are busy, so no need to spend much time on this. I can just ask you to restart when needed

**Comment by lmendo** [comment]
Not responding again (after I did some test with the Game of Life program)... Can you restart it when you have some time?

**Comment by suever** [comment]
Just did! That's strange that keeps happening. I wonder if when a job is cancelled it isn't completely cancelled or something

**Comment by lmendo** [comment]
Thanks! I'll just keep bugging you now and then when that happens, and problem solved :-D
