### ISSUE TITLE
Possible issue with string escaping

### ISSUE THREAD

**Issue by lmendo** [suever/MATL-Online#953]
Hello! I found a small issue with MATL Online. It seems to sometimes trip on `\` . I think it's related to character escaping. I noticed that the MATL statement `"` is escaped into `\"`. The character `\` is not escaped. When this character is at the very end of the code it "catches" the final double-qoute that should close the string passed to `matl_runner`, so the string is not closed. That's my interpretation, based on the error that shows up by running this:

https://matl.io/?code=%3A%22%405%5C3%5C&inputs=5&version=22.7.4

**Comment by suever** [comment]
@lmendo Addressed this in #972, thanks for the report and let me know if you run into any other oddities. Thanks!

**Comment by lmendo** [comment]
Thank you!
